### ISSUE TITLE
Simulator detection does not work on Apple Silicon

### ISSUE THREAD

**Issue by nathreed** [devexperts/suitcase#6]
**Describe the bug**

The extension on UIDevice that is used to detect whether a test case is running on a device or a simulator does not work on Apple Silicon machines. It assumes that any non-intel architecture cannot be a simulator, which is incorrect now that simulators run as arm64 on Apple Silicon.

**To Reproduce**
1. Run a SUITCase test on an Apple Silicon Mac with Xcode running natively.
2. Observe that you get an error message from SUITCase saying it does not support running on devices and supports simulators only.

**Expected behavior**
SUITCase should work on simulators running on Apple Silicon Macs. 

**Simulator (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.5
 - Xcode version: 13.4.1
 - macOS version: 12.3

**Additional context**
It should be a pretty simple fix to just use `#if targetEnvironment(simulator)` per https://stackoverflow.com/a/24869607/3163644.

**Comment by rzakhar** [comment]
Thank you for your report, the issue is fixed
